package ar.com.vault.hr.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import lombok.Getter;
import lombok.Setter;

/**
 * It represents the kind of jobs existing in the company.
 * 
 * @author Gaston Napoli
 *
 */
@Entity
@Table(name = "JOBS")
@Setter
@Getter
public class Job extends BaseEntity {

    /**
     * Non autogenerated/identity value, it has to be set on insert.
     */
    @Id
    @Column(name = "JOB_ID", nullable = false, length = 10)
    @Size(max = 10)
    private String id;

    @Column(name = "JOB_TITLE", length = 35)
    @Size(max = 35)
    private String title;
    
    @Column(name = "MIN_SALARY", length = 6)
    @Size(max = 6)
    private int minimumSalary;
    
    @Column(name = "MAX_SALARY", length = 6)
    @Size(max = 6)
    private int maximumSalary;
    
}
