package ar.com.vault.hr.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.hibernate.annotations.GenericGenerator;

import lombok.Getter;
import lombok.Setter;

/**
 * It represents locations in a country.
 * 
 * @author Gaston Napoli
 *
 */
@Entity
@Table(name = "LOCATIONS")
@Setter
@Getter
public class Location extends BaseEntity {

    /**
     * Autogenerated 4-digit number ID. 
     */
    @Id
    @GeneratedValue(
            strategy = GenerationType.AUTO,
            generator="native"
    )
    @GenericGenerator(
            name = "native",
            strategy = "native"
    )
    @Column(name = "LOCATION_ID", nullable = false, length = 4)
    @Max(9999)
    private Long id;
    
    @Column(name = "STREET_ADDRESS", length = 40)
    @Size(max = 40)
    private String streetAddress;
    
    @Column(name = "POSTAL_CODE", length = 12)
    @Size(max = 12)
    private String postalCode;
    
    @Column(name = "CITY", nullable = false, length = 30)
    @Size(max = 30)
    @NotNull
    private String city;
    
    @Column(name = "STATE_PROVINCE", length = 25)
    @Size(max = 25)
    private String stateProvince;
    
    /**
     * Many locations belong to a country.
     */
    @ManyToOne
    @JoinColumn(name = "COUNTRY_ID")
    @NotNull
    private Country country;
   
    @Override
    public String toString() {
       return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
}
