package ar.com.vault.hr.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;

import lombok.Getter;
import lombok.Setter;

/**
 * It represents regions.
 * 
 * @author Gaston Napoli
 *
 */
@Entity
@Table(name = "REGIONS")
@Setter
@Getter
public class Region extends BaseEntity {

    /**
     * Basic autogenerated number ID. 
     */
    @Id
    @GeneratedValue(
            strategy = GenerationType.AUTO,
            generator="native"
    )
    @GenericGenerator(
            name = "native",
            strategy = "native"
    )
    @Column(name = "REGION_ID", nullable = false)
    private Long id;
    
    @Column(name = "REGION_NAME", nullable = true, unique = true, length = 25)
    @Size(max = 25)
    private String name;
    
}
